### ISSUE TITLE
Relative paths don't work

### ISSUE THREAD

**Issue by acrash** [putnam/binmerge#7]
Hi,
I was trying to create a batch file in order to use your script quickly.
The batch file and the file [binmerge.py] are in the folder "C:\binmerge\"
My bin files are in "C:\binmerge\Bins\"
and I made a new folder "C:\binmerge\Merged\"

(Not working) This is the content of the .bat Batch file:
for /r %%i in (*.cue) do binmerge.py "%%i" "%%~ni.merged" -o "%~dp0\Merged\"

But it works with:
for /r %%i in (*.cue) do binmerge.py "%%i" "%%~ni.merged" -o "C:\binmerge\Merged\"

**Comment by putnam** [comment]
Thanks for the report

What is the output you get when running with a relative path? I'll test it out on Windows and see what's going on.

**Comment by putnam** [comment]
Is that really a relative path though? Shouldn't %~dp0 expand to an absolute path in the batch script and call binmerge with the expanded path?

**Comment by putnam** [comment]
Your problem lies in your use of %~dp0. It ends with a trailing backslash which ends up escaping a literal quote instead of closing the argument. This must be dealt with by your batch script. Your script is calling python with broken arguments as a result.

https://stackoverflow.com/questions/3160058/how-to-get-the-path-of-a-batch-script-without-the-trailing-backslash-in-a-single

You can just put a trailing . after it to fix it I guess. 

Try this instead:
for /r %%i in (*.cue) do binmerge.py "%%i" "%%~ni.merged" -o "%~dp0.\Merged"

**Comment by acrash** [comment]
Thank you man (for your response and for the program)
I'm an absolute idiot. Sorry if I wasted your time
